/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as DailyWavesRouteImport } from './routes/daily-waves'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as JoinRouteImport } from './routes/join'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MyWaveRouteRouteImport } from './routes/my-wave/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Season1RouteImport } from './routes/season-1'
import { Route as SeasonOneRouteImport } from './routes/season-one'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as WavesRouteImport } from './routes/waves'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as MyWaveIndexRouteImport } from './routes/my-wave/index'
import { Route as MyWaveDailyWavesRouteImport } from './routes/my-wave/daily-waves'
import { Route as MyWaveTodayRouteImport } from './routes/my-wave/today'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminActivitiesRouteImport } from './routes/_authenticated/admin/activities'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminParticipantsRouteImport } from './routes/_authenticated/admin/participants'
import { Route as AuthenticatedAdminSeasonRouteImport } from './routes/_authenticated/admin/season'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin/submissions'
import { Route as AuthenticatedAdminUnwindsRouteImport } from './routes/_authenticated/admin/unwinds'
import { Route as AuthenticatedFestivalArenaRouteImport } from './routes/_authenticated/festival/arena'
import { Route as AuthenticatedFestivalChampionsRouteImport } from './routes/_authenticated/festival/champions'
import { Route as AuthenticatedFestivalGalleryRouteImport } from './routes/_authenticated/festival/gallery'
import { Route as AuthenticatedFestivalLobbyRouteImport } from './routes/_authenticated/festival/lobby'
import { Route as AuthenticatedFestivalMapRouteImport } from './routes/_authenticated/festival/map'
import { Route as AuthenticatedFestivalPassportRouteImport } from './routes/_authenticated/festival/passport'
import { Route as AuthenticatedFestivalPlazaRouteImport } from './routes/_authenticated/festival/plaza'
import { Route as AuthenticatedFestivalStageRouteImport } from './routes/_authenticated/festival/stage'
import { Route as AuthenticatedFestivalVaultRouteImport } from './routes/_authenticated/festival/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyWavesRoute = DailyWavesRouteImport.update({
  id: '/daily-waves',
  path: '/daily-waves',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWaveRouteRoute = MyWaveRouteRouteImport.update({
  id: '/my-wave',
  path: '/my-wave',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Season1Route = Season1RouteImport.update({
  id: '/season-1',
  path: '/season-1',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonOneRoute = SeasonOneRouteImport.update({
  id: '/season-one',
  path: '/season-one',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const WavesRoute = WavesRouteImport.update({
  id: '/waves',
  path: '/waves',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MyWaveIndexRoute = MyWaveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyWaveRouteRoute,
} as any)
const MyWaveDailyWavesRoute = MyWaveDailyWavesRouteImport.update({
  id: '/daily-waves',
  path: '/daily-waves',
  getParentRoute: () => MyWaveRouteRoute,
} as any)
const MyWaveTodayRoute = MyWaveTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => MyWaveRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminActivitiesRoute =
  AuthenticatedAdminActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminParticipantsRoute =
  AuthenticatedAdminParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeasonRoute =
  AuthenticatedAdminSeasonRouteImport.update({
    id: '/season',
    path: '/season',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUnwindsRoute =
  AuthenticatedAdminUnwindsRouteImport.update({
    id: '/unwinds',
    path: '/unwinds',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedFestivalArenaRoute =
  AuthenticatedFestivalArenaRouteImport.update({
    id: '/festival/arena',
    path: '/festival/arena',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFestivalChampionsRoute =
  AuthenticatedFestivalChampionsRouteImport.update({
    id: '/festival/champions',
    path: '/festival/champions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFestivalGalleryRoute =
  AuthenticatedFestivalGalleryRouteImport.update({
    id: '/festival/gallery',
    path: '/festival/gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFestivalLobbyRoute =
  AuthenticatedFestivalLobbyRouteImport.update({
    id: '/festival/lobby',
    path: '/festival/lobby',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFestivalMapRoute =
  AuthenticatedFestivalMapRouteImport.update({
    id: '/festival/map',
    path: '/festival/map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFestivalPassportRoute =
  AuthenticatedFestivalPassportRouteImport.update({
    id: '/festival/passport',
    path: '/festival/passport',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFestivalPlazaRoute =
  AuthenticatedFestivalPlazaRouteImport.update({
    id: '/festival/plaza',
    path: '/festival/plaza',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFestivalStageRoute =
  AuthenticatedFestivalStageRouteImport.update({
    id: '/festival/stage',
    path: '/festival/stage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFestivalVaultRoute =
  AuthenticatedFestivalVaultRouteImport.update({
    id: '/festival/vault',
    path: '/festival/vault',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-wave': typeof MyWaveRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/daily-waves': typeof DailyWavesRoute
  '/experiences': typeof ExperiencesRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/join': typeof JoinRoute
  '/journey': typeof JourneyRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/season-1': typeof Season1Route
  '/season-one': typeof SeasonOneRoute
  '/showcase': typeof ShowcaseRoute
  '/stories': typeof StoriesRoute
  '/waves': typeof WavesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/my-wave/daily-waves': typeof MyWaveDailyWavesRoute
  '/my-wave/today': typeof MyWaveTodayRoute
  '/my-wave/': typeof MyWaveIndexRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/participants': typeof AuthenticatedAdminParticipantsRoute
  '/admin/season': typeof AuthenticatedAdminSeasonRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/unwinds': typeof AuthenticatedAdminUnwindsRoute
  '/festival/arena': typeof AuthenticatedFestivalArenaRoute
  '/festival/champions': typeof AuthenticatedFestivalChampionsRoute
  '/festival/gallery': typeof AuthenticatedFestivalGalleryRoute
  '/festival/lobby': typeof AuthenticatedFestivalLobbyRoute
  '/festival/map': typeof AuthenticatedFestivalMapRoute
  '/festival/passport': typeof AuthenticatedFestivalPassportRoute
  '/festival/plaza': typeof AuthenticatedFestivalPlazaRoute
  '/festival/stage': typeof AuthenticatedFestivalStageRoute
  '/festival/vault': typeof AuthenticatedFestivalVaultRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/daily-waves': typeof DailyWavesRoute
  '/experiences': typeof ExperiencesRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/join': typeof JoinRoute
  '/journey': typeof JourneyRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/season-1': typeof Season1Route
  '/season-one': typeof SeasonOneRoute
  '/showcase': typeof ShowcaseRoute
  '/stories': typeof StoriesRoute
  '/waves': typeof WavesRoute
  '/my-wave/daily-waves': typeof MyWaveDailyWavesRoute
  '/my-wave/today': typeof MyWaveTodayRoute
  '/my-wave': typeof MyWaveIndexRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/participants': typeof AuthenticatedAdminParticipantsRoute
  '/admin/season': typeof AuthenticatedAdminSeasonRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/unwinds': typeof AuthenticatedAdminUnwindsRoute
  '/festival/arena': typeof AuthenticatedFestivalArenaRoute
  '/festival/champions': typeof AuthenticatedFestivalChampionsRoute
  '/festival/gallery': typeof AuthenticatedFestivalGalleryRoute
  '/festival/lobby': typeof AuthenticatedFestivalLobbyRoute
  '/festival/map': typeof AuthenticatedFestivalMapRoute
  '/festival/passport': typeof AuthenticatedFestivalPassportRoute
  '/festival/plaza': typeof AuthenticatedFestivalPlazaRoute
  '/festival/stage': typeof AuthenticatedFestivalStageRoute
  '/festival/vault': typeof AuthenticatedFestivalVaultRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/my-wave': typeof MyWaveRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/daily-waves': typeof DailyWavesRoute
  '/experiences': typeof ExperiencesRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/join': typeof JoinRoute
  '/journey': typeof JourneyRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/season-1': typeof Season1Route
  '/season-one': typeof SeasonOneRoute
  '/showcase': typeof ShowcaseRoute
  '/stories': typeof StoriesRoute
  '/waves': typeof WavesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/my-wave/daily-waves': typeof MyWaveDailyWavesRoute
  '/my-wave/today': typeof MyWaveTodayRoute
  '/my-wave/': typeof MyWaveIndexRoute
  '/_authenticated/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/participants': typeof AuthenticatedAdminParticipantsRoute
  '/_authenticated/admin/season': typeof AuthenticatedAdminSeasonRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/unwinds': typeof AuthenticatedAdminUnwindsRoute
  '/_authenticated/festival/arena': typeof AuthenticatedFestivalArenaRoute
  '/_authenticated/festival/champions': typeof AuthenticatedFestivalChampionsRoute
  '/_authenticated/festival/gallery': typeof AuthenticatedFestivalGalleryRoute
  '/_authenticated/festival/lobby': typeof AuthenticatedFestivalLobbyRoute
  '/_authenticated/festival/map': typeof AuthenticatedFestivalMapRoute
  '/_authenticated/festival/passport': typeof AuthenticatedFestivalPassportRoute
  '/_authenticated/festival/plaza': typeof AuthenticatedFestivalPlazaRoute
  '/_authenticated/festival/stage': typeof AuthenticatedFestivalStageRoute
  '/_authenticated/festival/vault': typeof AuthenticatedFestivalVaultRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-wave'
    | '/about'
    | '/auth'
    | '/challenges'
    | '/community'
    | '/contact'
    | '/creators'
    | '/daily-waves'
    | '/experiences'
    | '/faqs'
    | '/forgot-password'
    | '/gallery'
    | '/hall-of-fame'
    | '/join'
    | '/journey'
    | '/live'
    | '/login'
    | '/missions'
    | '/register'
    | '/reset-password'
    | '/season-1'
    | '/season-one'
    | '/showcase'
    | '/stories'
    | '/waves'
    | '/admin'
    | '/my-wave/daily-waves'
    | '/my-wave/today'
    | '/my-wave/'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/participants'
    | '/admin/season'
    | '/admin/submissions'
    | '/admin/unwinds'
    | '/festival/arena'
    | '/festival/champions'
    | '/festival/gallery'
    | '/festival/lobby'
    | '/festival/map'
    | '/festival/passport'
    | '/festival/plaza'
    | '/festival/stage'
    | '/festival/vault'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/challenges'
    | '/community'
    | '/contact'
    | '/creators'
    | '/daily-waves'
    | '/experiences'
    | '/faqs'
    | '/forgot-password'
    | '/gallery'
    | '/hall-of-fame'
    | '/join'
    | '/journey'
    | '/live'
    | '/login'
    | '/missions'
    | '/register'
    | '/reset-password'
    | '/season-1'
    | '/season-one'
    | '/showcase'
    | '/stories'
    | '/waves'
    | '/my-wave/daily-waves'
    | '/my-wave/today'
    | '/my-wave'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/participants'
    | '/admin/season'
    | '/admin/submissions'
    | '/admin/unwinds'
    | '/festival/arena'
    | '/festival/champions'
    | '/festival/gallery'
    | '/festival/lobby'
    | '/festival/map'
    | '/festival/passport'
    | '/festival/plaza'
    | '/festival/stage'
    | '/festival/vault'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/my-wave'
    | '/about'
    | '/auth'
    | '/challenges'
    | '/community'
    | '/contact'
    | '/creators'
    | '/daily-waves'
    | '/experiences'
    | '/faqs'
    | '/forgot-password'
    | '/gallery'
    | '/hall-of-fame'
    | '/join'
    | '/journey'
    | '/live'
    | '/login'
    | '/missions'
    | '/register'
    | '/reset-password'
    | '/season-1'
    | '/season-one'
    | '/showcase'
    | '/stories'
    | '/waves'
    | '/_authenticated/admin'
    | '/my-wave/daily-waves'
    | '/my-wave/today'
    | '/my-wave/'
    | '/_authenticated/admin/activities'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/participants'
    | '/_authenticated/admin/season'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/unwinds'
    | '/_authenticated/festival/arena'
    | '/_authenticated/festival/champions'
    | '/_authenticated/festival/gallery'
    | '/_authenticated/festival/lobby'
    | '/_authenticated/festival/map'
    | '/_authenticated/festival/passport'
    | '/_authenticated/festival/plaza'
    | '/_authenticated/festival/stage'
    | '/_authenticated/festival/vault'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MyWaveRouteRoute: typeof MyWaveRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CreatorsRoute: typeof CreatorsRoute
  DailyWavesRoute: typeof DailyWavesRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  HallOfFameRoute: typeof HallOfFameRoute
  JoinRoute: typeof JoinRoute
  JourneyRoute: typeof JourneyRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Season1Route: typeof Season1Route
  SeasonOneRoute: typeof SeasonOneRoute
  ShowcaseRoute: typeof ShowcaseRoute
  StoriesRoute: typeof StoriesRoute
  WavesRoute: typeof WavesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-waves': {
      id: '/daily-waves'
      path: '/daily-waves'
      fullPath: '/daily-waves'
      preLoaderRoute: typeof DailyWavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-wave': {
      id: '/my-wave'
      path: '/my-wave'
      fullPath: '/my-wave'
      preLoaderRoute: typeof MyWaveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-1': {
      id: '/season-1'
      path: '/season-1'
      fullPath: '/season-1'
      preLoaderRoute: typeof Season1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-one': {
      id: '/season-one'
      path: '/season-one'
      fullPath: '/season-one'
      preLoaderRoute: typeof SeasonOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waves': {
      id: '/waves'
      path: '/waves'
      fullPath: '/waves'
      preLoaderRoute: typeof WavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/my-wave/': {
      id: '/my-wave/'
      path: '/'
      fullPath: '/my-wave/'
      preLoaderRoute: typeof MyWaveIndexRouteImport
      parentRoute: typeof MyWaveRouteRoute
    }
    '/my-wave/daily-waves': {
      id: '/my-wave/daily-waves'
      path: '/daily-waves'
      fullPath: '/my-wave/daily-waves'
      preLoaderRoute: typeof MyWaveDailyWavesRouteImport
      parentRoute: typeof MyWaveRouteRoute
    }
    '/my-wave/today': {
      id: '/my-wave/today'
      path: '/today'
      fullPath: '/my-wave/today'
      preLoaderRoute: typeof MyWaveTodayRouteImport
      parentRoute: typeof MyWaveRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/activities': {
      id: '/_authenticated/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/participants': {
      id: '/_authenticated/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AuthenticatedAdminParticipantsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/season': {
      id: '/_authenticated/admin/season'
      path: '/season'
      fullPath: '/admin/season'
      preLoaderRoute: typeof AuthenticatedAdminSeasonRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/unwinds': {
      id: '/_authenticated/admin/unwinds'
      path: '/unwinds'
      fullPath: '/admin/unwinds'
      preLoaderRoute: typeof AuthenticatedAdminUnwindsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/festival/arena': {
      id: '/_authenticated/festival/arena'
      path: '/festival/arena'
      fullPath: '/festival/arena'
      preLoaderRoute: typeof AuthenticatedFestivalArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festival/champions': {
      id: '/_authenticated/festival/champions'
      path: '/festival/champions'
      fullPath: '/festival/champions'
      preLoaderRoute: typeof AuthenticatedFestivalChampionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festival/gallery': {
      id: '/_authenticated/festival/gallery'
      path: '/festival/gallery'
      fullPath: '/festival/gallery'
      preLoaderRoute: typeof AuthenticatedFestivalGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festival/lobby': {
      id: '/_authenticated/festival/lobby'
      path: '/festival/lobby'
      fullPath: '/festival/lobby'
      preLoaderRoute: typeof AuthenticatedFestivalLobbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festival/map': {
      id: '/_authenticated/festival/map'
      path: '/festival/map'
      fullPath: '/festival/map'
      preLoaderRoute: typeof AuthenticatedFestivalMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festival/passport': {
      id: '/_authenticated/festival/passport'
      path: '/festival/passport'
      fullPath: '/festival/passport'
      preLoaderRoute: typeof AuthenticatedFestivalPassportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festival/plaza': {
      id: '/_authenticated/festival/plaza'
      path: '/festival/plaza'
      fullPath: '/festival/plaza'
      preLoaderRoute: typeof AuthenticatedFestivalPlazaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festival/stage': {
      id: '/_authenticated/festival/stage'
      path: '/festival/stage'
      fullPath: '/festival/stage'
      preLoaderRoute: typeof AuthenticatedFestivalStageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festival/vault': {
      id: '/_authenticated/festival/vault'
      path: '/festival/vault'
      fullPath: '/festival/vault'
      preLoaderRoute: typeof AuthenticatedFestivalVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminActivitiesRoute: typeof AuthenticatedAdminActivitiesRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminParticipantsRoute: typeof AuthenticatedAdminParticipantsRoute
  AuthenticatedAdminSeasonRoute: typeof AuthenticatedAdminSeasonRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminUnwindsRoute: typeof AuthenticatedAdminUnwindsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminActivitiesRoute: AuthenticatedAdminActivitiesRoute,
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminParticipantsRoute: AuthenticatedAdminParticipantsRoute,
    AuthenticatedAdminSeasonRoute: AuthenticatedAdminSeasonRoute,
    AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
    AuthenticatedAdminUnwindsRoute: AuthenticatedAdminUnwindsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFestivalArenaRoute: typeof AuthenticatedFestivalArenaRoute
  AuthenticatedFestivalChampionsRoute: typeof AuthenticatedFestivalChampionsRoute
  AuthenticatedFestivalGalleryRoute: typeof AuthenticatedFestivalGalleryRoute
  AuthenticatedFestivalLobbyRoute: typeof AuthenticatedFestivalLobbyRoute
  AuthenticatedFestivalMapRoute: typeof AuthenticatedFestivalMapRoute
  AuthenticatedFestivalPassportRoute: typeof AuthenticatedFestivalPassportRoute
  AuthenticatedFestivalPlazaRoute: typeof AuthenticatedFestivalPlazaRoute
  AuthenticatedFestivalStageRoute: typeof AuthenticatedFestivalStageRoute
  AuthenticatedFestivalVaultRoute: typeof AuthenticatedFestivalVaultRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFestivalArenaRoute: AuthenticatedFestivalArenaRoute,
  AuthenticatedFestivalChampionsRoute: AuthenticatedFestivalChampionsRoute,
  AuthenticatedFestivalGalleryRoute: AuthenticatedFestivalGalleryRoute,
  AuthenticatedFestivalLobbyRoute: AuthenticatedFestivalLobbyRoute,
  AuthenticatedFestivalMapRoute: AuthenticatedFestivalMapRoute,
  AuthenticatedFestivalPassportRoute: AuthenticatedFestivalPassportRoute,
  AuthenticatedFestivalPlazaRoute: AuthenticatedFestivalPlazaRoute,
  AuthenticatedFestivalStageRoute: AuthenticatedFestivalStageRoute,
  AuthenticatedFestivalVaultRoute: AuthenticatedFestivalVaultRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MyWaveRouteRouteChildren {
  MyWaveDailyWavesRoute: typeof MyWaveDailyWavesRoute
  MyWaveTodayRoute: typeof MyWaveTodayRoute
  MyWaveIndexRoute: typeof MyWaveIndexRoute
}

const MyWaveRouteRouteChildren: MyWaveRouteRouteChildren = {
  MyWaveDailyWavesRoute: MyWaveDailyWavesRoute,
  MyWaveTodayRoute: MyWaveTodayRoute,
  MyWaveIndexRoute: MyWaveIndexRoute,
}

const MyWaveRouteRouteWithChildren = MyWaveRouteRoute._addFileChildren(
  MyWaveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MyWaveRouteRoute: MyWaveRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CreatorsRoute: CreatorsRoute,
  DailyWavesRoute: DailyWavesRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  HallOfFameRoute: HallOfFameRoute,
  JoinRoute: JoinRoute,
  JourneyRoute: JourneyRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Season1Route: Season1Route,
  SeasonOneRoute: SeasonOneRoute,
  ShowcaseRoute: ShowcaseRoute,
  StoriesRoute: StoriesRoute,
  WavesRoute: WavesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
